### ISSUE TITLE
Error on fig up

### ISSUE THREAD

**Issue by stevepereira** [luiselizondo/docker-drupal-light#1]
Running on docker-osx:

...
Setting up php-apc (4.0.2-2build1) ...
rmdir: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.main", line 39, in main
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 21, in sys_dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.command", line 31, in dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 24, in dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.command", line 50, in perform_command
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 27, in perform_command
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.main", line 306, in up
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.project", line 131, in up
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 165, in recreate_containers
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 145, in create_container
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 293, in _get_container_create_options
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 312, in build
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 373, in stream_output
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 418, in print_output_event
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 22: ordinal not in range(128)

**Comment by luiselizondo** [comment]
I think the error is because it's defined volumes_from. Can you please change:

volumes_from:
- MYSQL_DATA

to

volumes_from: MYSQL_DATA

Also, fig does not have support for volumes_from, I think a commit was already made but it's not yet available in the binary, you can wait for the new version, compile the latest version for yourself or use volumes instead of volumes_from.

Note: What I mean when I say it does not have support, it means that somehow fig will recreate the container you pass as volumes_from so the data is not persisted and it doesn't really work the way it should.

**Comment by xiaods** [comment]
directly use boot2docker + docker 1.3, it can resolve it.
